language: python
  - 3.8

os:
  - linux

dist:
  - ubuntu

jobs:
  include:
    - stage: main
      name: lint
      before_script:
        - "pip install -r requirements_test.txt"
      script:
        - "yapf librec_auto --recursive --diff"
    - name: test
      before_script:
        - "pip install -r requirements_test.txt"
        - "python setup.py install"
      script:
        - "pytest --cov=librec_auto"
      after_success:
        - "coveralls"
