language: python
  - 3.8

os:
  - linux

jobs:
  include:
    - stage: "main"
      name: "install requirements"
      script:
        - "pip install -r requirements.txt"
        - "pip install -r requirements_test.txt"
        - "python setup.py install"
    - name: "lint"
      script:
        - "yapf librec_auto --recursive --diff"
    - name: "test"
      script:
        - "pytest --cov=librec_auto"
      after_success:
        - "coveralls"
