language: python
  - "3.8"
before_script:
  - "pip install -r requirements_test.txt"
  - "git clone https://github.com/schwartzadev/librec-auto"
  - "cd librec-auto"
script:
  - "pytest --cov=librec_auto"
after_success:
  - "coveralls"
