language: python
os:
  - linux
dist: xenial
jobs:
  include:
    - stage: main
      name: Lint
      before_script:
        - "pip install -r requirements_test.txt"
      script:
        - "yapf librec_auto --recursive --diff"
    - name: "Python Test"
      before_script:
        - "pip install -r requirements_test.txt"
        - "python setup.py install"
      script:
        - "coverage run --source=librec_auto -m pytest librec_auto/test/"
      after_success:
        - "coveralls"
    - name: "Build Docs"
      before_script:
        - "sudo apt-get install python3-sphinx"
        - "cd librec_auto/docs"
      script:
        - "make html"
