language: python
  - "3.8"

jobs:
  include:
    - stage: lint
      script:
        - "yapf librec_auto --recursive --diff"
    - stage: test
      before_script:
        - "pip install -r requirements.txt"
        - "pip install -r requirements_test.txt"
      script:
        - "pytest --cov=librec_auto"
      after_success:
        - "coveralls"
