language: python
  - 3.8

os:
  - linux

jobs:
  include:
    - stage: test
      name: "lint"
      before_script:
        - "pip install -r requirements_test.txt"
      script:
        - "yapf librec_auto --recursive --diff"
    - name: "test"
      before_script:
        - "pip install -r requirements.txt"
        - "pip install -r requirements_test.txt"
      script:
        - "pytest --cov=librec_auto"
      after_success:
        - "coveralls"
