name: librec-auto-ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Requirements
        run:
          - "pip install -r requirements_test.txt"
      - name: Lint with yapf
        run: "yapf librec_auto --recursive --diff"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Requirements
        run:
          - "pip install -r requirements.txt"
          - "pip install -r requirements_test.txt"
      - name: Install librec-auto
        run:
          - python setup.py install
      - name: Test Coverage
        run:
          - "coverage run --source=librec_auto -m pytest librec_auto/test/"
      - name: Test Coverage
        run:
          - "echo todo coveralls"
