name: Java CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Requirements
        run:
          - pip install -r requirements.txt
          - pip install -r requirements_test.txt
      - name: Lint with yapf
        run: yapf librec_auto --recursive --diff
